apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: priority-scheduler
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: priority-scheduler
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
