apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: priority-worker
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: priority-worker
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
